### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by mitchellrj** [petrilli/pyramid_transactional_celery#5]
This is a good-looking package, thanks!

The only thing I would question is its name: it doesn't require Pyramid at all. It might be better named as `zope.celery` or similar to follow the pattern set by `zope.sqlalchemy`.

**Comment by petrilli** [comment]
Thanks! A good point. Not sure whether changing the name midpoint a good idea, but I'll see if there's some way to rename it without existing packages losing the connection forward.

**Comment by petrilli** [comment]
Are you using it as a non-Pyramid package?
